Build:
  image: node:10
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

Deploy to npm:
  image: node:10
  stage: deploy
  before_script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
  script:
    - npm publish --access public
  only:
    - tags
  environment:
    name: npm
    url: https://www.npmjs.com/package/@opendataschema/table-schema-to-markdown
