Deploy to npm:
  image: node:10
  stage: deploy
  before_script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm install
  script:
    - npm publish --unsafe-perm --access public
  only:
    - tags
  environment:
    name: npm
    url: https://www.npmjs.com/package/@opendataschema/table-schema-to-markdown
